// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hocvien.Model;

namespace hocvien.Migrations
{
    [DbContext(typeof(centerContext))]
    [Migration("20230705083803_tam")]
    partial class tam
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("hocvien.Model.Cahoc", b =>
                {
                    b.Property<string>("Macahoc")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("macahoc")
                        .IsFixedLength(true);

                    b.Property<string>("Giohoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("giohoc");

                    b.Property<string>("Thuhoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("thuhoc");

                    b.HasKey("Macahoc")
                        .HasName("PK_NewTable");

                    b.ToTable("cahoc");
                });

            modelBuilder.Entity("hocvien.Model.Giaovien", b =>
                {
                    b.Property<string>("Magv")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("magv")
                        .IsFixedLength(true);

                    b.Property<string>("Capdoday")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("capdoday");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diachi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<int>("Gioitinh")
                        .HasColumnType("int")
                        .HasColumnName("gioitinh");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hoten");

                    b.Property<string>("Matkhau")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("matkhau");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaysinh");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaytao");

                    b.Property<string>("Nguoitao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nguoitao");

                    b.Property<int>("Sdt")
                        .HasColumnType("int")
                        .HasColumnName("SDT");

                    b.Property<string>("Trinhdo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("trinhdo");

                    b.HasKey("Magv")
                        .HasName("PK__giaovien__7A2118CDC4E0E876");

                    b.HasIndex(new[] { "Sdt" }, "UQ__giaovien__CA1930A5274DE8AF")
                        .IsUnique();

                    b.ToTable("giaovien");
                });

            modelBuilder.Entity("hocvien.Model.Hoadon", b =>
                {
                    b.Property<string>("Mahd")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("mahd")
                        .IsFixedLength(true);

                    b.Property<string>("Ghichu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ghichu");

                    b.Property<string>("Hinhthuc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinhthuc");

                    b.Property<string>("Manv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("manv")
                        .IsFixedLength(true);

                    b.Property<string>("Maphieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("maphieu")
                        .IsFixedLength(true);

                    b.Property<DateTime>("Ngaythu")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaythu");

                    b.Property<decimal>("Sotienconlai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sotiendatra")
                        .HasColumnType("money");

                    b.Property<decimal>("Tongtienthanhtoan")
                        .HasColumnType("money")
                        .HasColumnName("tongtienthanhtoan");

                    b.Property<string>("Trangthaithanhtoan")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("trangthaithanhtoan");

                    b.HasKey("Mahd")
                        .HasName("PK__hoadon__7A2100DE7B55A670");

                    b.HasIndex(new[] { "Manv" }, "IX_hoadon_manv");

                    b.HasIndex(new[] { "Maphieu" }, "IX_hoadon_maphieu");

                    b.ToTable("hoadon");
                });

            modelBuilder.Entity("hocvien.Model.Hocvien", b =>
                {
                    b.Property<string>("Mahv")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("mahv")
                        .IsFixedLength(true);

                    b.Property<string>("Diachi")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("diachi");

                    b.Property<int>("Gioitinh")
                        .HasColumnType("int")
                        .HasColumnName("gioitinh");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("hoten");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaysinh");

                    b.Property<DateTime?>("Ngaytao")
                        .HasColumnType("date")
                        .HasColumnName("ngaytao");

                    b.Property<string>("Nguoitao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nguoitao");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sdt");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("trangthai");

                    b.HasKey("Mahv")
                        .HasName("PK__hocvien__7A2100ACCDE8976F");

                    b.ToTable("hocvien");
                });

            modelBuilder.Entity("hocvien.Model.Khoahoc", b =>
                {
                    b.Property<string>("Makh")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("makh")
                        .IsFixedLength(true);

                    b.Property<string>("Motakh")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("motakh");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("date")
                        .HasColumnName("ngaytao");

                    b.Property<string>("Nguoitao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nguoitao");

                    b.Property<string>("Tenkh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenkh");

                    b.Property<string>("Thoiluong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("thoiluong");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangthai");

                    b.HasKey("Makh")
                        .HasName("PK__khoahoc__7A21BB4CEC06FD83");

                    b.ToTable("khoahoc");
                });

            modelBuilder.Entity("hocvien.Model.LopDangkyhoc", b =>
                {
                    b.Property<string>("Maphieu")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("maphieu")
                        .IsFixedLength(true);

                    b.Property<string>("Maloptuyensinh")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("maloptuyensinh")
                        .IsFixedLength(true);

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Maphieu", "Maloptuyensinh")
                        .HasName("PK__lop_dang__667414EAC3CA8403");

                    b.HasIndex(new[] { "Maloptuyensinh" }, "IX_lop_dangkyhoc_maloptuyensinh");

                    b.ToTable("lop_dangkyhoc");
                });

            modelBuilder.Entity("hocvien.Model.Lophoc", b =>
                {
                    b.Property<string>("Malophoc")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .IsFixedLength(true);

                    b.Property<string>("Magv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maloptuyensinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("maloptuyensinh")
                        .IsFixedLength(true);

                    b.Property<string>("Phonghoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("phonghoc");

                    b.HasKey("Malophoc")
                        .HasName("PK__lophoc__03B4ED841809EB80");

                    b.HasIndex(new[] { "Maloptuyensinh" }, "IX_lophoc_maloptuyensinh");

                    b.ToTable("lophoc");
                });

            modelBuilder.Entity("hocvien.Model.LophocGiaovien", b =>
                {
                    b.Property<string>("Malophoc")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("malophoc")
                        .IsFixedLength(true);

                    b.Property<string>("Magv")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("magv")
                        .IsFixedLength(true);

                    b.HasKey("Malophoc", "Magv")
                        .HasName("PK__lophoc_g__C416FC08AA169897");

                    b.HasIndex(new[] { "Magv" }, "IX_lophoc_giaovien_magv");

                    b.ToTable("lophoc_giaovien");
                });

            modelBuilder.Entity("hocvien.Model.Loptuyensinh", b =>
                {
                    b.Property<string>("Maloptuyensinh")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("maloptuyensinh")
                        .IsFixedLength(true);

                    b.Property<string>("Giohoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("giohoc");

                    b.Property<string>("Macahoc")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("macahoc")
                        .IsFixedLength(true);

                    b.Property<string>("Makh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("makh")
                        .IsFixedLength(true);

                    b.Property<string>("Mamh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("mamh")
                        .IsFixedLength(true);

                    b.Property<DateTime>("Ngaybatdau")
                        .HasColumnType("date")
                        .HasColumnName("ngaybatdau");

                    b.Property<DateTime>("Ngayketthuc")
                        .HasColumnType("date")
                        .HasColumnName("ngayketthuc");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("date")
                        .HasColumnName("ngaytao");

                    b.Property<string>("Nguoitao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nguoitao");

                    b.Property<string>("Tenloptuyensinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenloptuyensinh");

                    b.Property<string>("Thuhoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("thuhoc");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("trangthai");

                    b.HasKey("Maloptuyensinh")
                        .HasName("PK__loptuyen__15F456FDA9F7C730");

                    b.HasIndex("Macahoc");

                    b.HasIndex(new[] { "Makh" }, "IX_loptuyensinh_makh");

                    b.HasIndex(new[] { "Mamh" }, "IX_loptuyensinh_mamh");

                    b.ToTable("loptuyensinh");
                });

            modelBuilder.Entity("hocvien.Model.Monhoc", b =>
                {
                    b.Property<string>("Mamh")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("mamh")
                        .IsFixedLength(true);

                    b.Property<decimal>("Hocphi")
                        .HasColumnType("money")
                        .HasColumnName("hocphi");

                    b.Property<string>("Mota")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("mota");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("date")
                        .HasColumnName("ngaytao");

                    b.Property<string>("Nguoitao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nguoitao");

                    b.Property<string>("Tenmh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenmh");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangthai");

                    b.HasKey("Mamh")
                        .HasName("PK__monhoc__7A21CB8E6E58B74A");

                    b.ToTable("monhoc");
                });

            modelBuilder.Entity("hocvien.Model.Nhanvien", b =>
                {
                    b.Property<string>("Manv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("manv")
                        .IsFixedLength(true);

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("diachi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<byte>("Gioitinh")
                        .HasColumnType("tinyint")
                        .HasColumnName("gioitinh");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("hoten");

                    b.Property<string>("Matkhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaysinh");

                    b.Property<int>("Nhom")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("nhom");

                    b.Property<int>("Sdt")
                        .HasColumnType("int")
                        .HasColumnName("sdt");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("trangthai");

                    b.HasKey("Manv")
                        .HasName("manv");

                    b.HasIndex(new[] { "Sdt" }, "UQ__nhanvien__DDDFB4832ACE57B4")
                        .IsUnique();

                    b.ToTable("nhanvien");
                });

            modelBuilder.Entity("hocvien.Model.Phieudangkyhoc", b =>
                {
                    b.Property<string>("Maphieu")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("maphieu")
                        .IsFixedLength(true);

                    b.Property<string>("Ghichu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ghichu");

                    b.Property<string>("Mahv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("mahv")
                        .IsFixedLength(true);

                    b.Property<string>("Manv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("manv")
                        .IsFixedLength(true);

                    b.Property<DateTime?>("Ngaydk")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaydk");

                    b.HasKey("Maphieu")
                        .HasName("PK__phieudan__A72B5185C862877D");

                    b.HasIndex("Manv");

                    b.HasIndex(new[] { "Mahv" }, "IX_phieudangkyhoc_mahv");

                    b.ToTable("phieudangkyhoc");
                });

            modelBuilder.Entity("hocvien.Model.Phieudiem", b =>
                {
                    b.Property<string>("Malophoc")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("malophoc")
                        .IsFixedLength(true);

                    b.Property<string>("Mahv")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("mahv")
                        .IsFixedLength(true);

                    b.Property<int?>("Diemdoc")
                        .HasColumnType("int")
                        .HasColumnName("diemdoc");

                    b.Property<int?>("Diemnghe")
                        .HasColumnType("int")
                        .HasColumnName("diemnghe");

                    b.Property<int?>("Diemnoi")
                        .HasColumnType("int")
                        .HasColumnName("diemnoi");

                    b.Property<int?>("Diemviet")
                        .HasColumnType("int")
                        .HasColumnName("diemviet");

                    b.Property<int>("Trangthai")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("trangthai");

                    b.HasKey("Malophoc", "Mahv")
                        .HasName("PK__phieudie__D416FD8EF39C6EED");

                    b.HasIndex(new[] { "Mahv" }, "IX_phieudiem_mahv");

                    b.ToTable("phieudiem");
                });

            modelBuilder.Entity("hocvien.Model.Hoadon", b =>
                {
                    b.HasOne("hocvien.Model.Nhanvien", "ManvNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FKhoadon404248")
                        .IsRequired();

                    b.HasOne("hocvien.Model.Phieudangkyhoc", "MaphieuNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Maphieu")
                        .HasConstraintName("FKhoadon89696")
                        .IsRequired();

                    b.Navigation("ManvNavigation");

                    b.Navigation("MaphieuNavigation");
                });

            modelBuilder.Entity("hocvien.Model.LopDangkyhoc", b =>
                {
                    b.HasOne("hocvien.Model.Loptuyensinh", "MaloptuyensinhNavigation")
                        .WithMany("LopDangkyhocs")
                        .HasForeignKey("Maloptuyensinh")
                        .HasConstraintName("FKlop_dangky847460")
                        .IsRequired();

                    b.HasOne("hocvien.Model.Phieudangkyhoc", "MaphieuNavigation")
                        .WithMany("LopDangkyhocs")
                        .HasForeignKey("Maphieu")
                        .HasConstraintName("FKlop_dangky777448")
                        .IsRequired();

                    b.Navigation("MaloptuyensinhNavigation");

                    b.Navigation("MaphieuNavigation");
                });

            modelBuilder.Entity("hocvien.Model.Lophoc", b =>
                {
                    b.HasOne("hocvien.Model.Loptuyensinh", "MaloptuyensinhNavigation")
                        .WithMany("Lophocs")
                        .HasForeignKey("Maloptuyensinh")
                        .HasConstraintName("FKlophoc12899")
                        .IsRequired();

                    b.Navigation("MaloptuyensinhNavigation");
                });

            modelBuilder.Entity("hocvien.Model.LophocGiaovien", b =>
                {
                    b.HasOne("hocvien.Model.Giaovien", "MagvNavigation")
                        .WithMany("LophocGiaoviens")
                        .HasForeignKey("Magv")
                        .HasConstraintName("FKlophoc_gia956872")
                        .IsRequired();

                    b.HasOne("hocvien.Model.Lophoc", "MalophocNavigation")
                        .WithMany("LophocGiaoviens")
                        .HasForeignKey("Malophoc")
                        .HasConstraintName("FKlophoc_gia710147")
                        .IsRequired();

                    b.Navigation("MagvNavigation");

                    b.Navigation("MalophocNavigation");
                });

            modelBuilder.Entity("hocvien.Model.Loptuyensinh", b =>
                {
                    b.HasOne("hocvien.Model.Cahoc", "MacahocNavigation")
                        .WithMany("Loptuyensinhs")
                        .HasForeignKey("Macahoc")
                        .HasConstraintName("FKloptuyensinhch");

                    b.HasOne("hocvien.Model.Khoahoc", "MakhNavigation")
                        .WithMany("Loptuyensinhs")
                        .HasForeignKey("Makh")
                        .HasConstraintName("FKloptuyensi996854")
                        .IsRequired();

                    b.HasOne("hocvien.Model.Monhoc", "MamhNavigation")
                        .WithMany("Loptuyensinhs")
                        .HasForeignKey("Mamh")
                        .HasConstraintName("FKloptuyensi77378")
                        .IsRequired();

                    b.Navigation("MacahocNavigation");

                    b.Navigation("MakhNavigation");

                    b.Navigation("MamhNavigation");
                });

            modelBuilder.Entity("hocvien.Model.Phieudangkyhoc", b =>
                {
                    b.HasOne("hocvien.Model.Hocvien", "MahvNavigation")
                        .WithMany("Phieudangkyhocs")
                        .HasForeignKey("Mahv")
                        .HasConstraintName("FKphieudangk163725")
                        .IsRequired();

                    b.HasOne("hocvien.Model.Nhanvien", "ManvNavigation")
                        .WithMany("Phieudangkyhocs")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FKphieudangkyhocnv");

                    b.Navigation("MahvNavigation");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("hocvien.Model.Phieudiem", b =>
                {
                    b.HasOne("hocvien.Model.Hocvien", "MahvNavigation")
                        .WithMany("Phieudiems")
                        .HasForeignKey("Mahv")
                        .HasConstraintName("FKphieudiem797904")
                        .IsRequired();

                    b.HasOne("hocvien.Model.Lophoc", "MalophocNavigation")
                        .WithMany("Phieudiems")
                        .HasForeignKey("Malophoc")
                        .HasConstraintName("FKphieudiem484564")
                        .IsRequired();

                    b.Navigation("MahvNavigation");

                    b.Navigation("MalophocNavigation");
                });

            modelBuilder.Entity("hocvien.Model.Cahoc", b =>
                {
                    b.Navigation("Loptuyensinhs");
                });

            modelBuilder.Entity("hocvien.Model.Giaovien", b =>
                {
                    b.Navigation("LophocGiaoviens");
                });

            modelBuilder.Entity("hocvien.Model.Hocvien", b =>
                {
                    b.Navigation("Phieudangkyhocs");

                    b.Navigation("Phieudiems");
                });

            modelBuilder.Entity("hocvien.Model.Khoahoc", b =>
                {
                    b.Navigation("Loptuyensinhs");
                });

            modelBuilder.Entity("hocvien.Model.Lophoc", b =>
                {
                    b.Navigation("LophocGiaoviens");

                    b.Navigation("Phieudiems");
                });

            modelBuilder.Entity("hocvien.Model.Loptuyensinh", b =>
                {
                    b.Navigation("LopDangkyhocs");

                    b.Navigation("Lophocs");
                });

            modelBuilder.Entity("hocvien.Model.Monhoc", b =>
                {
                    b.Navigation("Loptuyensinhs");
                });

            modelBuilder.Entity("hocvien.Model.Nhanvien", b =>
                {
                    b.Navigation("Hoadons");

                    b.Navigation("Phieudangkyhocs");
                });

            modelBuilder.Entity("hocvien.Model.Phieudangkyhoc", b =>
                {
                    b.Navigation("Hoadons");

                    b.Navigation("LopDangkyhocs");
                });
#pragma warning restore 612, 618
        }
    }
}
